---
title: "Lab 00 - Hello IDS!"
author: "JulietteMB2008"
date: "30/09/2026"
output: html_document
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
```

### Exercises 16-17 - Did not get this done in class. 

We set up the data frame. Edit the data below to include information about your team members.

```{r setup-tibble}
team_data <- tibble(
  name = c("Juliette", "A", "B", 
           "C", "D"),
  github_username = c("JulietteMB2008", "A", "B", 
                      "C", "D"), 
  colour = c("powderblue", "plum", "aliceblue", 
             "blueviolet", "yellowgreen"),
  hobby = c("Piano", "Running", "Knitting", 
            "Drawing", "Figure Skating"),
  favourite_number = c(3, 5, 7, 9, 1)
  )

team_data
```

### Exercise 18

We now work on visualising our data. 

```{r bar-plot}
p1 <- ggplot(data = team_data, 
             mapping = aes(x = github_username, 
                           y = favourite_number,
                           fill = colour), 
             ) +
   geom_col() +
   scale_fill_identity()
p1
```

The plot shows favourite number against GitHub username in the user's favourite colour.

